### ISSUE TITLE
[FEATURE] Test Code 작성

### ISSUE THREAD

**Issue by Jisu00** [DevelopLife/reviewtwits_frontend#118]
## 📌  개요

- 내용을 작성해주세요

<br>

## 💻  기능 설명

- 어떤 기능인지 자세히 설명해주세요.

<br>

## ✅  참고 사항

- 해당 기능 개발과 관련된 이슈나, 자료를 적어주세요.

<br>

## 📷  스크린 샷
- 기능 요청에 대한 다른 내용 또는 스크린 샷을 함께 올려주세요.

**Comment by ahn0min** [comment]
컴포넌트를 테스트 하기 편하게 변경한 후에 테스트코드 작성을 진행하기로 결정하였습니다.
