### ISSUE TITLE
[BUG] Next Image를 통한 외부 이미지 최적화 오류 개선

### ISSUE THREAD

**Issue by Jisu00** [DevelopLife/reviewtwits_frontend#133]
## 👉  버그 설명

> Uncaught RangeError: Wrong length!

로컬 이미지가 아닌 외부 이미지를 가져와서 Next Image 컴포넌트로 렌더링을 할 경우, 위와 같은 에러가 발생합니다.
개발 초반에는 외부 이미지 문제 없이 렌더링 되다가 어느 순간부터 이러한 에러가 발생하여 일단 급하게 아래와 같은 회피 방법을 찾긴 하였습니다.

```tsx
import Image from 'next/image';

...

return (
  <Image unoptimized={true} ... />
);
```

`unoptimized` 적용 시 잘 동작하는 것으로 보아 이미지 최적화에 관련하여 문제가 있는 것으로 파악됩니다.
하지만 `unoptimized` 속성을 사용할 경우, Next Image를 사용하는 주요 이유인 이미지 최적화를 사용할 수 없기 때문에 반드시 해결해야 할 것 같습니다.
함께 고민하여 해결해보면 좋을 것 같아 이슈로 등록합니다.

<br>

## ✅  해결 방법

- 버그를 어떻게 해결했는지 적어주세요.

1. 원인
2. 방법
3. 결과

<br>

## 📷  스크린 샷

- 가능한 경우 문제를 파악하는 데 도움이 되는 스크린 샷을 추가해주세요.

<br>

## ⭐ 추가 내용

- 문제를 해결하는 데 참고했던 자료의 링크를 공유해주세요.

**Comment by ahn0min** [comment]
어떤 브랜치에서 해당 에러를 확인해볼 수 있을까요?

**Comment by Jisu00** [comment]
> 어떤 브랜치에서 해당 에러를 확인해볼 수 있을까요?

develop에서 `unoptimized`가 적용된 Image 컴포넌트에 속성을 주석 처리해보시면 확인할 수 있을 것 같습니다.

**Comment by ahn0min** [comment]
![image](https://user-images.githubusercontent.com/89904226/232205415-9f058b64-b778-4148-b972-70de9c0598bb.png)


Next.js Image 이미지 최적화랑 naveridlogin_js_sdk.js를 함께 사용하면 문제가 발생하는것 같아요
naveridlogin_js_sdk_2.0.0 을 2.0.2로 버전을 변경하면 해당 에러는 해결되는 것 같습니다.

- #134 PR 확인 부탁드립니다!
