### ISSUE TITLE
[SUGGEST] VScode의 Code Snippets를 이용하여 반복 작업의 효율 향상시키기

### ISSUE THREAD

**Issue by ahn0min** [DevelopLife/reviewtwits_frontend#136]
## 📌  개요

프론트엔드 작업에서 반복적으로 작성하게 되는 코드는 아래와 같습니다.
- React Function __Component__
- React __Custom Hook__
- __Story__ Code
- __Test__ Code

여태까지 저는 키보드의 쫀득함을 손가락으로 느끼며 이런 작업들을 진행해 왔습니다.
VScode에서는 Github Issue, PR Template 처럼 자동으로 사전에 작성해둔 코드 템플릿을 불러올 수 있는 __Code Snippets__ 을 지원합니다.
이제부터는 그 쫀득함을 내부 로직 작성에서만 느낄 수 있도록 __Code Snippets__ 기능을 이용하여 반복작성하는 코드를 자동화화려고 합니다.🤭

> _진지하지 않아 보일 수 있으나 매우 진지합니다.. Code Snippets을 도입하면 반복작업의 피로도를 줄여줄 것으로 예상됩니다.  :)_

이 제안이 approve 된다면 Component, Hook, Story, Test 파일에서 사용할 수 있도록  Code Snippets에 대한 작업을 진행하고
사용법을 Wiki에다가 작성하도록 하겠습니다.

<br>

## 💻  기능 설명
- Component, Hook, Story, Test를 커스텀 멍령어를 통해 쉽게 작성 가능

<br>

## ✅  참고 사항

'어떻게하면 다른 팀원들이 추가적인 작업을 해주지 않아도 Code Snippets을 이용할 수 있을까?' 란 고민을 하면서 3가지 방법을 고려했으며 3번으로 결정하였습니다.

1. VScode Extension으로 만들기 (복잡한것 같아요)
2. npm package로 배포하기 (package가 버전업 될 때마다 새롭게 install 해주어야 합니다. 불편함)
3. .vscode 내부 폴더에서 `{language}.vscode-snippets` 파일로 작성하기 (이걸 제일 늦게 알아버려서 고생이란 고생은 다한 것 같네요...) 👍

<br>

## 📷  스크린 샷
![image](https://user-images.githubusercontent.com/89904226/232297305-75cec81a-673c-498c-8f66-2cfc4423bfff.png)

**Comment by ahn0min** [comment]
@Jisu00 , @userJu 읽어보시고 comment 남겨주세요!!

**Comment by Jisu00** [comment]
도입하면 좋을 것 같네요!

**Comment by ahn0min** [comment]
[WIKI](https://github.com/DevelopLife/reviewtwits_frontend/wiki/Code-Snippets) 작성 완료했습니다.

**Comment by userJu** [comment]
확인했습니다! 👍👍 반복작업을 줄여주어 좋을 것 같아요!
